In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [2]:
data = load_iris()

In [3]:
dir(data)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
X = data.data
y = data.target

In [5]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [6]:
y[0]

0

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [8]:
model_lr = LogisticRegression()
model_lr.fit(X_train, y_train)
model_lr.score(X_test, y_test)

c:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [9]:
model_rfc = RandomForestClassifier()
model_rfc.fit(X_train, y_train)
model_rfc.score(X_test, y_test)

0.9333333333333333

In [10]:
model_svm = SVC()
model_svm.fit(X_train, y_train)
model_svm.score(X_test, y_test)

0.9666666666666667

In [11]:
def get_score(model, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [12]:
Kfold = StratifiedKFold(n_splits=4)

In [13]:
score_logistic = []
score_rfc = []
score_svm = []

In [14]:
for train_index, test_index in Kfold.split(X, y):
    X_train = data.data[train_index]
    X_test = data.data[test_index]

    y_train = data.target[train_index]
    y_test = data.target[test_index]

    score_logistic.append(get_score(LogisticRegression(), X_train, y_train, X_test, y_test))
    score_rfc.append(get_score(RandomForestClassifier(), X_train, y_train, X_test, y_test))
    score_svm.append(get_score(SVC(), X_train, y_train, X_test, y_test))

c:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [15]:
score_logistic

[0.9736842105263158, 0.9736842105263158, 0.9459459459459459, 1.0]

In [16]:
score_rfc

[0.9736842105263158, 0.9473684210526315, 0.9459459459459459, 0.972972972972973]

In [17]:
score_svm

[0.9736842105263158, 1.0, 0.9459459459459459, 0.972972972972973]

In [18]:
# cross_val_score does the same thing as above but in a more efficient way
scores_logistic1 = cross_val_score(LogisticRegression(), X, y, cv=Kfold)
scores_rfc1 = cross_val_score(RandomForestClassifier(), X, y, cv=Kfold)
scores_svm1 = cross_val_score(SVC(), X, y, cv=Kfold)

c:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [19]:
scores_logistic1

array([0.97368421, 0.97368421, 0.94594595, 1.        ])

In [20]:
scores_rfc1

array([0.97368421, 0.94736842, 0.94594595, 0.97297297])

In [21]:
scores_svm1

array([0.97368421, 1.        , 0.94594595, 0.97297297])

In [22]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=3),X, y, cv=10)
np.average(scores1)

0.9533333333333334

In [23]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=10),X, y, cv=10)
np.average(scores2)

0.96

In [29]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),X, y, cv=10)
np.average(scores3)

0.9533333333333334